name: Sync LeetCode Today Problem

on:
  workflow_dispatch:
  schedule:
    # Runs at 5:05 PST
    - cron: "5 0 * * *"

jobs:
  create_leetcode_daily_practice_issue:
    runs-on: ubuntu-latest
    name: create daily practice issue
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create daily practice issue action step
        uses: xingorg1/leetcode-daily-practice-action@main
        with:
          token: ${{secrets.TOKEN}}
  sync_leetcode_today_record_job:
    name: sync leetcode today problem job
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode Today Problem
        uses: spencercjh/sync-leetcode-today-problem@0.4.3
        with:
          language: Python3
