name: Sync LeetCode Today Problem

on:
  workflow_dispatch:
  schedule:
    # Runs at 5:05 PST
    - cron: "5 0 * * *"

jobs:
  sync_leetcode_today_record_job:
    name: sync leetcode today problem job
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode Today Problem
        uses: spencercjh/sync-leetcode-today-problem@<latest version>
        with:
          language: Python3
