name: Sync LeetCode Today Problem

on:
  workflow_dispatch:
  schedule:
    # Runs at 17:20 PST
    - cron: "7 0 * * *"

jobs:
  create_leetcode_daily_practice_issue:
    runs-on: ubuntu-latest
    name: create daily practice issue
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create daily practice issue action step
        uses: jeremypruitt/gha-github-issue-for-leetcode-daily@master
        env:
          DEBUG: 1
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
