name: Sync LeetCode Today Problem

on:
  workflow_dispatch:
  schedule:
    # Runs at 17:07 PST
    - cron: "7 0 * * *"

jobs:
  create_leetcode_daily_practice_issue:
    runs-on: ubuntu-latest
    name: Create Github issues for LC daily problem
    permissions:
      issues: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Get daily LC problem and create new GitHub issue
        uses: jeremypruitt/gha-github-issue-for-leetcode-daily@master
